
server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/the-world
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

app:
  client:
    url: http://localhost:4200/*
#
#    git remote add origin https://github.com/Abdelaziz-100/every-one-back.git
#    git branch -M main
#    git push -u origin main

